module.exports = {
    USER_COLL: 'users',
    DB_NAME: process.env.DB_NAME || 'bcd-cms',
    REFRESH_TOKEN_COLL: 'refreshTokens',
    ISO_MASTER_DATA_COLL: 'iso_codes',
    CONTAINER_DETAILS: 'containerDetails',
    IGM_INFO_DETAILS: 'igmInfoDetails',
    CARGO_DETAILS: 'cargoDetails',
    CONTAINERS: 'containers',
    MACHINES: 'machines',
    FREIGHT_STATIONS: 'freightStations',
    SLOTS: 'slots',
    JOB_CARDS: 'job_cards',
    MOVEMENT_LOGS: 'movement_logs',
    CONTAINER_SIZES: 'containerSizes',
    CONTAINER_TYPES: 'containerTypes',
    CONTAINER_STATUSES: 'containerStatuses',
    BUCKETS: 'buckets',
    DEMO: 'demo',
    SEQUENCE : "sequences",
    ORGANIZATIONS: 'organizations',
    YARDS: 'yards',
    ROLES: 'roles',
    TRAILERS: 'trailers',
    GENERIC_ERR_LOG : 'error_log',
    USR_ACT_LOG : 'activityLog',
    MACHINE_MOVEMENTS: 'machineMovements',
    NOTIFICATION_LOG : 'notificationLog',
    NOTIFICATION_LOG_HIST : 'notificationLogHist',
    EMAIL_LOG : 'emailLog',
    EMAIL_LOG_HIST : 'emailLogHist',
    MOBILES: 'mobileDevices',
	PROCESSING_DEVICES: 'processingDevices',
	CAMERA: 'cameraDevices',
    GPS: 'gpsDevices',
    DAMAGE_LEVEL: 'damageLevel',
    PRIORITY: 'priority',
    PURPOSE: 'purpose',
    MOVEMENT_TYPES: 'movementTypes',
    ZONE: 'zone',
    MACHINE_BREAKDOWN_DETAILS:'machineBreakdownDetails'
}
